name: LaTeX Build and Spellcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: main.pdf
          
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up aspell
        run: sudo apt-get install aspell aspell-en
        
      - name: Run spellcheck
        run: |
          for file in $(find . -type f -name '*.tex' -o -name '*.md'); do
            echo "Checking $file"
            aspell --lang=en --mode=tex list < "$file" | sort -u
          done
        continue-on-error: true